# Generated by Django 5.2.5 on 2025-08-23 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('publish_date', models.DateField()),
                ('media_type', models.CharField(choices=[('podcast', 'Podcast'), ('documentary', 'Documentary'), ('show', 'Show'), ('other', 'Other')], default='other', max_length=20)),
                ('media_url', models.URLField(help_text='Direct link to the media (e.g., YouTube video)')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Optional: link to program thumbnail/cover', null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='cms.category')),
            ],
        ),
    ]
